Don't hardcode many properties and try to inherit as much as possible
freebsd/poudriere pull request #814
Opened 2020-12-27 13:46 UTC by Duffyx

This should fix issue 794.

I just need to get some insight if the createfs is used for anything else besides creating jails or port trees. As the mountpoint is not needed for ZFS it will just be inherited from the top dataset. Not sure if I'm missing something.

2020-12-27 13:55 UTC, Duffyx reviewed
We could also just get rid of the -p, if we create the jail dataset in common.sh.

2021-01-16 17:32 UTC, bdrewery requested changes

2021-01-16 17:32 UTC, bdrewery commented on src/share/poudriere/include/fs.sh
> +		if ! zfs create -p ${fs}; then
Yeah let's drop the `-p` here. If it fails trying to create outside of the ZROOTFS then something else is broken.

2021-01-16 17:32 UTC, bdrewery commented on src/share/poudriere/common.sh
> +			-o compression=lz4 \
I think this should just be `compression=on`.

>       Setting compression to on indicates that the current default compression algorithm should be used.  The default balances compression and decompression speed, with compression ratio and is expected to work well on a wide variety of workloads.  Unlike all other settings for this property, on does not select a
>       fixed compression type.  As new compression algorithms are added to ZFS and enabled on a pool, the default compression algorithm may change.  The current default compression algorithm is either lzjb or, if the lz4_compress feature is enabled, lz4.

> if the lz4_compress feature is enabled, lz4.

That is also more in spirit of #794.

2021-01-16 19:28 UTC, bdrewery approved these changes

2021-01-16 19:28 UTC, bdrewery commented
Thanks!

2021-01-16 19:29 UTC, merged