Improvements to poudriere-bulk.8
freebsd/poudriere pull request #963
Opened 2021-12-07 08:36 UTC by 0mp

A general clean up and some wordsmithing.

I'm not sure about this part though:

```
With this option
.Nm poudriere
will first try to fetch a binary package
from the specified binary package repository
and only then check if the package already exist.
```

What do we want to tell the user about here?

2022-06-18 03:29 UTC, bdrewery commented
> With this option
.Nm poudriere
will first try to fetch a binary package
from the specified binary package repository

keep

> and only then check if the package already exist.

The part isn't needed anymore. The fetching tries to be smart enough to not do needless fetches.

2022-06-18 03:29 UTC, bdrewery requested changes

2022-06-18 03:29 UTC, bdrewery commented on src/man/poudriere-bulk.8
> +and only then check if the package already exist.
This last part can drop

2022-06-29 09:49 UTC, 0mp commented
Done.

2022-06-29 14:47 UTC, merged